project:
  type: website
  output-dir: docs

website:
  title: "Dominique J. Strong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: yeti
    css: styles.css
