project:
  type: website

website:
  title: "Dominique J Strong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: darkly

# <-- These lines ensure Python chunks run via Jupyter -->
execute:
  enabled: true
  echo: true
  warning: false
  message: false
jupyter: python3



