project:
  type: website

website:
  title: "Dominique J Strong"

format:
  html:
    theme: cosmo

# <-- These lines ensure Python chunks run via Jupyter -->
execute:
  enabled: true
  echo: true
  warning: false
  message: false
jupyter: python3



