project:
  type: website

website:
  title: "Dominique J Strong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Projects.qmd
        text: Projects
      - href: CV.qmd
        text: Curriculum Vitae
      - href: contact.qmd
        text: Contact Me

format:
  html:
    theme: yeti

# <-- These lines ensure Python chunks run via Jupyter -->
execute:
  enabled: true
  echo: true
  warning: false
  message: false
jupyter: python3



